ALTER TABLE users
    ADD COLUMN IF NOT EXISTS company_name TEXT,
    ADD COLUMN IF NOT EXISTS inn VARCHAR(12),
    ADD COLUMN IF NOT EXISTS kpp VARCHAR(9),
    ADD COLUMN IF NOT EXISTS ogrn VARCHAR(13),
    ADD COLUMN IF NOT EXISTS bank_name TEXT,
    ADD COLUMN IF NOT EXISTS bik VARCHAR(9),
    ADD COLUMN IF NOT EXISTS bank_account VARCHAR(20),
    ADD COLUMN IF NOT EXISTS corr_account VARCHAR(20),
    ADD COLUMN IF NOT EXISTS legal_address TEXT;

CREATE TABLE IF NOT EXISTS user_documents (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    file_path TEXT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
